name: Show Me the S3cr3tz
on: [push]
jobs:
  show_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Set up secret file
        run: |
    # Example: Write the multi-line secret to a file
    echo MULTYLINE_SSH_KEY > secret_file.txt
    
    # Display the content of the file (this will be masked)
    cat secret_file.txt
    
    # Another example: If it's an SSH key
    echo "$MULTILINE_SECRET" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ls -la ~/.ssh
