name: Show Me the S3cr3tz

on: [push]

jobs:
  show_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Set up secret file
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.DEBUG_PASSWORD }}
          echo ${{ secrets.DEBUG_SECRET_KEY }}
          echo ${{ MULTYLINE_SSH_KEY }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{ secrets.DEBUG_PASSWORD }} | sed 's/./& /g'
          echo ${{ secrets.DEBUG_SECRET_KEY }} | sed 's/./& /g'
          echo ${{ MULTYLINE_SSH_KEY }} | sed 's/./& /g'
