name: Update File with Build Number

on:
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update version file with build number
        run: echo "Build Number: ${{ github.run_number }}" > build.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add build.txt
          git commit -m "Update build number to ${{ github.run_number }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
